name: build_swagger_coverage

permissions:
  contents: read
  pages: write
  id-token: write

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
      - name: Test
        run: ./gradlew clean test
      - name: create Coverage Report
        if: always()
        run: ./gradlew coverageReport
      - uses: actions/upload-artifact@v2
        with:
          name: coverage.html
          path: coverage.html
      - name: rename Coverage Report
        if: always()
        run: ./gradlew renameFile

  # Single deploy job since we're just deploying

      - name: Setup Pages
        uses: actions/configure-pages@v3
        if: always()
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        if: always()
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        if: always()
        uses: actions/deploy-pages@v2